const dummyData2 = {
  result: {
    List1: {
      title: "지금 핫한 MALL",
      subTitle: "",
      data: [
        {
          id: 1,
          name: "지마켓",
          category: "종합/쇼핑몰",
          img: "https://mblogthumb-phinf.pstatic.net/20160902_225/ppanppane_1472800031988GvjHu_PNG/%C1%F6%B8%B6%C4%CF_%B7%CE%B0%ED_%281%29.png?type=w800",
          link: "https://www.gmarket.co.kr/",
        },
        {
          id: 2,
          name: "베리스토어",
          category: "팬/쇼핑몰",
          img: "https://tp.rmoa.net/data/dapp/EiuhJiQuWcgOWyxScCzo9bYzOZkXkC.jpg",
          link: "https://berrystore.co.kr/",
        },
        {
          id: 3,
          name: "쿠팡",
          category: "종합/쇼핑몰",
          img: "https://cloudfront-ap-northeast-1.images.arcpublishing.com/chosun/CW44FNVZBFNU7IDC2UNOFUPS3A.jpg",
          link: "https://www.coupang.com/",
        },
        {
          id: 4,
          name: "마켓블리",
          category: "식품/쇼핑몰",
          img: "https://tp.rmoa.net/data/dapp/5HwBiUGpCuomNbQHfFxTfGm1Zk5LJT.jpg",
          link: "https://marketbly.com/",
        },
      ],
    },
    List2: {
      title: "최근에 나온 게임🎮",
      subTitle: "",
      data: [
        {
          id: 1,
          name: "쿠키런 킹덤",
          category: "캐주얼/게임",
          img: "https://www.cookierun-kingdom.com/og-ko.jpg",
          link: "https://www.cookierun-kingdom.com/ko/",
        },
        {
          id: 2,
          name: "R-Planet",
          category: "블록체인/게임",
          img: "https://tp.rmoa.net/data/dapp/4x1mqqN9js840XllweleNAyQSTa8Hf.jpg",
          link: "https://rplanet.io/generator",
        },
        {
          id: 3,
          name: "슈월드",
          category: "게임",
          img: "https://tp.rmoa.net/data/dapp/DJguqVH21XoyfcFoVRcBAi9VKuR5By.jpg",
          link: "https://pt.rmoa.net/shop/food/1",
        },
        {
          id: 4,
          name: "슈월드",
          category: "게임",
          img: "https://tp.rmoa.net/data/dapp/DJguqVH21XoyfcFoVRcBAi9VKuR5By.jpg",
          link: "https://pt.rmoa.net/shop/food/1",
        },
      ],
    },
    List3: {
      title: "플레이리스트 🎵",
      subTitle: "",
      data: [
        {
          id: 1,
          name: "슈박스",
          category: "음악/엔터",
          img: "https://subox.co.kr/img/about1.png",
          link: "https://subox.co.kr/",
        },
        {
          id: 2,
          name: "SM town",
          category: "종합/엔터",
          img: "https://th.bing.com/th/id/OIP.JbZzN4Z92F-ftI4efhcLmQHaDn?pid=ImgDet&rs=1",
          link: "https://www.smtown.com/",
        },
        {
          id: 3,
          name: "Somesing",
          category: "음악/엔터",
          img: "https://www.techm.kr/news/photo/202104/82187_81413_4319.png",
          link: "https://www.somesing.io/index",
        },
        {
          id: 4,
          name: "HYBE",
          category: "종합/엔터",
          img: "https://pbs.twimg.com/media/E1Sa7utVkAEZRpS.jpg",
          link: "https://hybecorp.com/eng/main",
        },
      ],
    },
    List4: {
      title: "지금 인기 많은 메인넷",
      subTitle: "",
      data: [
        {
          id: 1,
          name: "HYPERCHAIN 2.0",
          category: "메인넷",
          img: "https://tp.rmoa.net/data/dapp/DJguqVH21XoyfcFoVRcBAi9VKuR5By.jpg",
          link: "https://www.cookierun-kingdom.com/ko/",
        },
        {
          id: 2,
          name: "비트코인",
          category: "메인넷",
          img: "https://image.chosun.com/sitedata/image/201712/27/2017122701549_0.jpg",
          link: "https://rplanet.io/generator",
        },
        {
          id: 3,
          name: "이더리움",
          category: "메인넷",
          img: "https://blog.overbit.com/content/images/2020/12/Ethereum-overbit.jpg",
          link: "https://eos.cryptodynasty.one/",
        },
        {
          id: 4,
          name: "이오스",
          category: "메인넷",
          img: "https://www.blockmedia.co.kr/wp-content/uploads/2019/03/EOS.png",
          link: "https://na.leagueoflegends.com/ko-kr/",
        },
      ],
    },
    List5: {
      title: "지금 인기 많은 지갑 💰",
      subTitle: "",
      data: [
        {
          id: 1,
          name: "P2P SUWALLET",
          category: "하이퍼체인/지갑",
          img: "https://play-lh.googleusercontent.com/mnxmHM1cbaxkWiRXEa45ubEktha-rvSJa5cNNOS1_WzEps2VR4IkM3pP8RVefTdOMTf0=s180-rw",
          link: "https://play.google.com/store/apps/details?id=org.sucon.suwallet",
        },
        {
          id: 2,
          name: "MyEtherWallet",
          category: "이더리움/지갑",
          img: "https://www.myetherwallet.com/img/mew-icon.de3130df.png",
          link: "https://www.myetherwallet.com/",
        },
        {
          id: 3,
          name: "코인베이스월렛",
          category: "거래소/지갑",
          img: "https://joind.io/attach/article/1616546929020Fc20t.jpg",
          link: "https://wallet.coinbase.com/",
        },
        {
          id: 4,
          name: "NOVA wallet",
          category: "이오스/지갑",
          img: "https://s3.ap-northeast-2.amazonaws.com/eosnova.io.resource/image2.0/download-nova-img.png",
          link: "https://www.eosnova.io/",
        },
      ],
    },
    List6: {
      title: "지금 인기 많은 마이닝 ⛏",
      subTitle: "",
      data: [
        {
          id: 1,
          name: "마이닝 풀 허브",
          category: "마이닝",
          img: "https://tp.rmoa.net/data/dapp/FBLQLKndopWYg5NWU9hDmpH4W7yQEi.jpg",
          link: "https://miningpoolhub.com/",
        },
        {
          id: 2,
          name: "Bitcoin Pool",
          category: "마이닝",
          img: "https://tp.rmoa.net/data/dapp/vGN58v6fdTiiQdfGdFL3e8DtqhggyZ.jpg",
          link: "https://console.pool.bitcoin.com/login",
        },
        {
          id: 3,
          name: "제네시스 마이닝",
          category: "마이닝",
          img: "https://pbs.twimg.com/profile_images/966889613930381312/JkaTgfQ6_400x400.jpg",
          link: "https://www.genesis-mining.com/",
        },
        {
          id: 4,
          name: "팟 마이닝",
          category: "마이닝",
          img: "https://pbs.twimg.com/profile_images/1209373686639104000/HZFvaCKz_400x400.jpg",
          link: "http://www.potmining.com/",
        },
      ],
    },
    List7: {
      title: "지금 인기 많은 커뮤니티✨",
      subTitle: "",
      data: [
        {
          id: 1,
          name: "코박",
          category: "커뮤니티",
          img: "https://tp.rmoa.net/data/dapp/T9Oa0cxN6XNaVRAXDuj6CF0VdpaTyi.jpg",
          link: "https://cobak.co.kr/",
        },
        {
          id: 2,
          name: "해시넷",
          category: "커뮤니티",
          img: "https://tp.rmoa.net/data/dapp/OSt8akw2P4niyjKnlabdQBiPWwBcul.jpg",
          link: "http://www.hash.kr/",
        },
        {
          id: 3,
          name: "땡글",
          category: "커뮤니티",
          img: "https://tp.rmoa.net/data/dapp/DJguqVH21XoyfcFoVRcBAi9VKuR5By.jpg",
          link: "https://www.ddengle.com/",
        },
        {
          id: 4,
          name: "블록체인 허브",
          category: "커뮤니티",
          img: "https://tp.rmoa.net/data/dapp/uXTsCO97bAvraSlwThJcAVForgrrSk.jpg",
          link: "https://blockchainhub.kr/",
        },
      ],
    },
    Card1: {
      title: "추천 🎁",
      subTitle: "",
      data: [
        {
          id: 1,
          name: "지마켓",
          category: "종합/쇼핑",
          img: "https://www.enewstoday.co.kr/news/photo/201911/1347449_411130_4141.jpg",
          subImg:
            "https://mblogthumb-phinf.pstatic.net/20160902_225/ppanppane_1472800031988GvjHu_PNG/%C1%F6%B8%B6%C4%CF_%B7%CE%B0%ED_%281%29.png?type=w800",
          link: "https://www.gmarket.co.kr/",
        },
        {
          id: 2,
          name: "슈박스,모두의 미디어",
          category: "음악/엔터",
          img: "https://subox.co.kr/img/about1.png",
          subImg: "https://subox.co.kr/img/logo.png",
          link: "https://subox.co.kr/",
        },
        {
          id: 3,
          name: "Bora",
          category: "엔터",
          img: "https://th.bing.com/th/id/OIP.QUoDZMAb0DB5RzxMmssW8QHaFS?w=246&h=180&c=7&o=5&pid=1.7",
          subImg:
            "https://tp.rmoa.net/data/dapp/JAy7q726mktBdB6X6BjxInmgDnsLns.jpg",
          link: "https://www.boraecosystem.com/",
        },
        {
          id: 4,
          name: "베리스토어",
          category: "스타/쇼핑",
          img: "https://th.bing.com/th/id/OIP.KJkHXfGsspIk9XolBZe1gwHaEK?w=325&h=182&c=7&o=5&pid=1.7",
          subImg:
            "https://play-lh.googleusercontent.com/a0CnHztbft04j6SlOck6rA7-k4f2yM-qh7qazoaBtLTdVJLbzFFw12tmjf4QlE3JrVo=s180-rw",
          link: "https://berrystore.co.kr/",
        },
      ],
    },
    Ad1: {
      data: [
        {
          id: 1,
          name: "바나나톡",
          category: "ad",
          img: "https://pbs.twimg.com/profile_banners/1133707102239617024/1620275628/1500x500",
          link: "http://bananatok.io/",
        },
        {
          id: 2,
          name: "bybit x 석류차트",
          category: "ad",
          img: "https://blockchainhub.kr/data/file/event/3717479908_O8i2AbJT_d1b35fd9afecd91ff58a821e727b0d31bb084f81.jpg",
          link: "https://www.bybit.com/ko-KR/bonusbash/",
        },
        {
          id: 3,
          name: "유한킴벌리",
          category: "ad",
          img: "https://ssl.pstatic.net/tveta/libs/1344/1344138/8bea5459c587299474d3_20210603155413212.jpg",
          link: "https://happybean.naver.com/flower/event/24",
        },
      ],
    },
    Event1: {
      data: [
        {
          id: 1,
          name: "Mission Impossible - Project No1.LOG",
          subName: "제로원",
          category: "event",
          img: "https://cm.rmoa.net/data/file/profit_con/thumb-2038932219_iSzXrUOP_18e820508d536a2daa61d08a7a134869ad8cc739_835x595.png",
          link: "http://pt.rmoa.net/",
          startdate: "2021-06-25",
          enddate: "2021-09-01",
        },
        {
          id: 2,
          name: "뉴스레터를 열면 TPC가 쏟아진다!",
          subName: "토큰포스트",
          category: "event",
          img: "https://www.tokenpost.kr/assets/uploads/20210614_bc_cb1473b129694.png",
          link: "https://www.tokenpost.kr/event/513",
          startdate: "2021-06-20",
          enddate: "2021-08-20",
        },
        {
          id: 3,
          name: "'블록체인으로 혁신하는 디지털 경제' 정책 컨퍼런스",
          subName: "과학기술정보통신부",
          category: "event",
          img: "https://th.bing.com/th/id/Rd30012e177af73d10cc489cc2490dd5b?rik=6Pgrvf7WEAdW8w&riu=http%3a%2f%2fres.heraldm.com%2fcontent%2fimage%2f2018%2f07%2f03%2f20180703000635_0.jpg&ehk=1HmEid6hH7x8r7evRn41j6a5vWT%2bSIoQXYQMc24AYQM%3d&risl=&pid=ImgRaw",
          link: "https://www.tokenpost.kr/event/507",
          startdate: "2021-06-15",
          enddate: "2021-07-30",
        },
      ],
    },
  },
};

export default dummyData2;
